# Generated by Django 5.0.2 on 2024-03-27 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjecttest',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tests/media/images'),
        ),
    ]
