# Generated by Django 5.0.2 on 2024-04-14 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatetest',
            name='language',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='generatetest',
            name='subject1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='generatetest',
            name='subject2',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='generatetest',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
