# Generated by Django 5.0.2 on 2024-05-19 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_checksheetresult_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjecttest',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='userfile',
            name='file',
            field=models.FileField(upload_to='userfile/'),
        ),
    ]
