# Generated by Django 5.0.2 on 2024-04-14 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_generatetest_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatetest',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language', to='api.language'),
        ),
        migrations.AlterField(
            model_name='generatetest',
            name='subject1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_1', to='api.subject'),
        ),
        migrations.AlterField(
            model_name='generatetest',
            name='subject2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_2', to='api.subject'),
        ),
        migrations.AlterField(
            model_name='generatetest',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to='api.ctuser'),
        ),
    ]
