# Generated by Django 5.0.2 on 2024-04-28 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_generatetest_language_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='tests/inputfile')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ctuser')),
            ],
        ),
        migrations.CreateModel(
            name='CheckSheetResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='tests/outputfile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ctuser')),
            ],
        ),
    ]
