# Generated by Django 5.0.2 on 2024-05-21 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_subjecttest_image_alter_userfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checksheet',
            name='book_id',
            field=models.CharField(blank=True, default='None', max_length=20, null=True),
        ),
    ]
