# Generated by Django 5.0.2 on 2024-05-21 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_checksheet_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checksheet',
            name='book_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
